name: Coverage
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: x64
    - run: pip install poetry
    - run: poetry install --no-root
    - run: poetry run pytest --cov src
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}